# Generated by Django 4.2.30 on 2026-06-10 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_price_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Categorías adicionales del producto', related_name='extra_products', to='catalog.category'),
        ),
    ]
